platform :ios, '13.0'
use_frameworks!

target 'ExKit_Example' do
  pod 'ExKit', :path => '../'

  target 'ExKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
